// svelte-spending-app/src/components/SpendingChart.svelte
<script lang="ts">
    import * as echarts from "echarts";
    import { onMount, onDestroy } from "svelte";
  
    interface Spending {
      userId: number;
      count: number;
      type: string;
    }
  
    export let data: Spending[] = []; // Initialize with an empty array
    let chartEl: HTMLDivElement;
  
    // Aggregate data function
    const aggregateData = (data: Spending[]) => {
      const aggregated: Record<string, number> = {};
  
      data.forEach(({ type, count }) => {
        if (aggregated[type]) {
          aggregated[type] += count;
        } else {
          aggregated[type] = count;
        }
      });
  
      return Object.entries(aggregated).map(([type, count]) => ({
        type,
        count,
      }));
    };
  
    let chart: echarts.ECharts | null = null;
  
    // Function to set up the chart
    const setupChart = () => {
      if (chart) {
        chart.dispose();
      }
      chart = echarts.init(chartEl);
      const aggregatedData = aggregateData(data);
  
      const option = {
        tooltip: {},
        xAxis: {
          type: "category",
          data: aggregatedData.map((item) => item.type),
        },
        yAxis: {
          type: "value",
        },
        series: [
          {
            data: aggregatedData.map((item) => item.count),
            type: "bar",
            barWidth: "60%",
          },
        ],
      };
  
      chart.setOption(option);
    };
  
    // Setup chart on mount and whenever data changes
    onMount(() => {
      setupChart();
    });
  
    $: if (data.length > 0) {
      setupChart(); // Update chart whenever data changes
    }
  
    // Cleanup chart on component unmount
    onDestroy(() => {
      if (chart) {
        chart.dispose();
      }
    });
  </script>
  
  <!-- Chart container -->
  <div bind:this={chartEl} class="w-full h-96">chart</div>

// react-spending-app/src/components/charts/SpendingChart.tsx
import React from 'react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend } from 'recharts';

interface Spending {
  userId: number;
  count: number;
  type: string;
}

// Aggregate data function
const aggregateData = (data: Spending[]) => {
    const aggregated: Record<string, number> = {};
  
    data.forEach(({ type, count }) => {
      if (aggregated[type]) {
        aggregated[type] += count;
      } else {
        aggregated[type] = count;
      }
    });
  
    return Object.entries(aggregated).map(([type, count]) => ({
      type,
      count,
    }));
  };

const SpendingChart: React.FC<{ data: Spending[] }> = ({ data }) => {
    const aggregatedData = aggregateData(data);

  return (
    <BarChart width={600} height={300} data={aggregatedData}>
      <CartesianGrid strokeDasharray="3 3" />
      <XAxis dataKey="type" />
      <YAxis />
      <Tooltip />
      <Legend />
      <Bar dataKey="count" fill="#82ca9d" />
    </BarChart>
  );
};

export default SpendingChart;
